### ISSUE TITLE
title page text gradient doesnt cover the entirety of the text

### ISSUE THREAD

**Issue by neurokitti** [zen-browser/www#185]
the gradient applied to the text on the main page is a bit off and shows a gray portion in the bottom right.

![image](https://github.com/user-attachments/assets/9dfa4cae-db09-4fea-b9e5-76d14c8e1f21)

I checked and this happens at all zoom levels and window sizes.

in other browsers (i tried arc)
it just cuts off

![image](https://github.com/user-attachments/assets/c2fdcbe2-4989-4a9a-90af-e0f91de92bc0)

**Comment by mauro-balades** [comment]
Fixed, thanks!

**Comment by neurokitti** [comment]
how often does the website update? I checked an the issue is still there for me
